# Site settings
title: Patrick Tinsley (PT)
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Patrick Tinsley (PT)
user_description: I'm a PhD candidate at the University of Notre Dame studying face recognition and synthetic biometrics.
user_title: AI/ML Research Scientist
email: ptinsley@nd.edu
# twitter_username: lorem_ipsum
# instagram_username: mauriciourraco7
facebook_username: pgtinsley
linkedin_username: pgtinsley
github_username:  pgtinsley
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
