# Site settings
title:          PT
description:    "I am a third-year member of the CVRL @ the University of Notre Dame. My focus is latent space representation in the context of re-identification and synthetic image generation."
url:            https://pgtinsley.github.io/

# Author
author:
  name:         PT
  email:        ptinsley@nd.edu
  url:          https://tinsleyzoo.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Related posts settings
related_posts_section:
  max_count:        5
  min_common_tags:  2

# Links to social media
social:
  email: ptinsley@nd.edu
  github: https://github.com/pgtinsley
  twitter: https://twitter.com/pgtinsley
  linkedin: https://ba.linkedin.com/in/pgtinsley
  scholar: https://scholar.google.com/citations?hl=en&user=ZLuTa3gAAAAJ
